spring.application.name=tastee-backend
# spring.security.user.name=user
# spring.security.user.password=password
# spring.security.user.roles=USER
spring.datasource.url=jdbc:postgresql://localhost:5432/tasteedb
# spring.datasource.username=postgres
# spring.datasource.password=postgres
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create-drop

